name: SubServer
version: '${project.version}'
main: com.stackmc.subserver.SubServer
api-version: '26.2'
authors: [LoanSpac, Clooooud, Bloupyi]
commands:
  subserver:
    description: "SubServer's main command"
    permission: subserver.admin
permissions:
  subserver.admin:
    description: "Acces aux commandes d'administration de SubServer"
    default: op
